### ISSUE TITLE
Update parser to work with quickfix-jruby 1.6.5

### ISSUE THREAD

**Issue by daino3** [connamara/logstash-filter-fix_protocol#84]
Or pin the parser to use 1.6.0. 

```
NoMethodError:
        undefined method `get_field_type_enum' for #<LogStash::Filters::DataDictionary:0x122635ef>
```

used [here](https://github.com/connamara/logstash-filter-fix_protocol/blob/master/lib/logstash/filters/fix_message.rb#L35)

**Comment by daino3** [comment]
closed per #85
